config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new,:create,:show]

  resources :sessions
  
  resources :blogs do
    collection do
      post 'confirm'
    end
  end

  resources :favorites,only:[:create,:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title,length:{minimum:1,maximum:50}
  validates :content,length:{minimum:1,maximum:140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true,length:{maximum:30},uniqueness: true
  validates :email,presence: true,length:{maximum:255},format:{with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  before_validation { email.downcase! }
  has_secure_password

  validates :password,presence: true,length: { minimum:6 }
  has_many :blogs
  has_many :favorites,dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render 'new'
    end
  end


  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title,:content)
  end




end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url,notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = currnte_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url,notice:"#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'log in failed'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice]="logged out!"
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_path
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    else
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true,url: choose_path ) do |f| %>
  <div class="blog_title">
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>
  <div class="blog_title">
    <%= f.label :content%>
    <%= f.text_area :content%>
  </div>
  <%= f.submit %>
<% end %>

app/views/blogs/confirm.html.erb
<h1>投稿確認</h1>
<%= form_with(model:@blog,loca:true ) do |f| %>
  <%= f.hidden_field :title %>
  <p><%= @blog.title %></p>
  <%= f.hidden_field :content %>
  <p><%= @blog.content %></p>
  <%= f.submit 'submit' %>
<% end %>

<%= form_with(model: @blog,local: true,url: new_blog_path,method: :get)do |f|%>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "back",name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>一覧表示</h1>
<table>
  <tr>
    <th>title</th>
    <th>content</th>
    <th>user</th>
    <th>detail</th>
    <th>edit</th>
    <th>delete</th>
  <% @blogs.each do |blog| %>
    </tr>
      <td><%= blog.title  %></td>
      <td><%= blog.content %></td>
      <td><%= blog.user.name%></td>
      <td><%= link_to 'dtl', blog_path(blog.id) %></td>
      <td><%= link_to 'edt',edit_blog_path(blog.id)  %></td>
      <td><%= link_to 'dlt', blog_path(blog.id),method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to "新規作成",new_blog_path %>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>
<%= render 'form'%>

app/views/blogs/show.html.erb
<h1>詳細</h1>
<p><%= @blog.title %></p>
<p><%= @blog.content %></p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to "お気に入りを解除する",favorite_path(id: @favorite.id,class:'btn btn-danger') %>
  <% else %>
    <%= link_to 'お気に入りにする',favorites_path(blog_id: @blog.id),method: :post,class:'btn btn-primary'%>
  <% end %>
<% end %>


<%= link_to 'back to index', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLoginSecond</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key,value| %>
      <%= content_tag(:div,value,class: "#{key}")%>
    <% end %>
    <% if logged_in? %>
      <%= link_to 'Profile', user_path(current_user.id) %>
      <%= link_to 'Log out', session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_path %>
      <%= link_to 'Log in', new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user,local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :password %>
  <%= form.text_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.text_field :password_confirmation %>

  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>